// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesteGrownt.Infrastructure.Data;

#nullable disable

namespace TesteGrownt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126113754_MakeDepartamentoOpcional")]
    partial class MakeDepartamentoOpcional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TesteGrownt.Domain.Entities.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RG")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("RG")
                        .IsUnique();

                    b.ToTable("Colaboradores", (string)null);
                });

            modelBuilder.Entity("TesteGrownt.Domain.Entities.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartamentoSuperiorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GerenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoSuperiorId");

                    b.HasIndex("GerenteId");

                    b.ToTable("Departamentos", (string)null);
                });

            modelBuilder.Entity("TesteGrownt.Domain.Entities.Colaborador", b =>
                {
                    b.HasOne("TesteGrownt.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Colaboradores")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("TesteGrownt.Domain.Entities.Departamento", b =>
                {
                    b.HasOne("TesteGrownt.Domain.Entities.Departamento", "DepartamentoSuperior")
                        .WithMany("SubDepartamentos")
                        .HasForeignKey("DepartamentoSuperiorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TesteGrownt.Domain.Entities.Colaborador", "Gerente")
                        .WithMany()
                        .HasForeignKey("GerenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepartamentoSuperior");

                    b.Navigation("Gerente");
                });

            modelBuilder.Entity("TesteGrownt.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("SubDepartamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
